session_name: open-magnate
windows:
  - window_name: frontend
    panes:
      - shell_command:
        - nvim ./frontend
        split: horizontal
        size: 70

      - shell_command:
        - cd ./frontend
        - npm run dev
        split: horizontal
        size: 30

  - window_name: backend
    panes:
      - shell_command:
        - nvim ./backend
        split: horizontal
        size: 70

      - shell_command:
        - cd ./backend
        - npm run dev
        split: horizontal
        size: 30

  - window_name: Lazy Git
    panes:
      - shell_command:
        - lazygit

