services:
    db:
        image: mysql
        restart: always
        container_name: integration-tests-prisma
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: tests
            MYSQL_USER: prisma
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        expose:
            - 3307
        volumes:
            - open-magnate-db:/var/lib/mysql

volumes:
    open-magnate-db:
