-- AlterTable
ALTER TABLE `game_state` ADD COLUMN `turnProgress` ENUM('PREGAME', 'SETTING_UP', 'RESTAURANT_PLACEMENT', 'RESTRUCTURING', 'TURN_ORDER_SELECTION', 'USE_EMPLOYEES', 'SALARY_PAYOUTS', 'MARKETING_CAMPAIGNS', 'CLEAN_UP', 'POSTGAME') NOT NULL DEFAULT 'PREGAME';
