name: Push Open Magnate
run-name: Push to ${{ github.ref_name }} by @${{ github.actor }}
on: [push]
jobs:
    Test-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "22"

            - name: Download Dependencies
              run: |
                  npm ci
                  cd ./backend
                  npm ci

            - name: Migrate the database
              run: |
                  cd ./backend
                  npm run migrate

            - name: Run Tests
              run: |
                  cd ./backend
                  npm test
