name: Push Open Magnate
run-name: Push to ${{ github.ref_name }} by @${{ github.actor }}
on: [push]
jobs:
    Test-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Change to backend directory
              run: cd ./backend

            - name: Download Dependencies
              run: |
                  npm ci
                  cd ./backend
                  npm ci

            - name: Run Tests
              run: |
                  cd ./backend
                  npm test

